USE CLIENTS;

CREATE TABLE IF NOT EXISTS SALES (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  CLIENT_ID INT NOT NULL,
  TOTAL_AMOUNT DECIMAL(10, 2) NOT NULL,
  SALE_TYPE ENUM('Varejo', 'Atacado') NOT NULL,
  PAYMENT_METHOD ENUM('Cartão de Crédito', 'Cartão de Débito', 'Dinheiro', 'Pix', 'Boleto') NOT NULL,
  SALE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(ID)
);
