USE CLIENTS;

CREATE TABLE IF NOT EXISTS SALES (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  CLIENT_ID INT NOT NULL,
  DISCOUNT DECIMAL(5, 4) NOT NULL DEFAULT 0 CHECK (DISCOUNT >= 0),
  CASHBACK DECIMAL(10, 2) NOT NULL DEFAULT 0 CHECK (CASHBACK >= 0),
  TOTAL_AMOUNT DECIMAL(10, 2) NOT NULL,
  SALE_TYPE ENUM('Varejo', 'Atacado') NOT NULL,
  PAYMENT_METHOD ENUM('Crédito', 'Débito', 'Dinheiro', 'Pix', 'Promissoria', 'QR Pix') NOT NULL,
  SALE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(ID)
);
