CREATE DATABASE IF NOT EXISTS CLIENTS;
USE CLIENTS;

CREATE TABLE IF NOT EXISTS CLIENTS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  CPF VARCHAR(11) NOT NULL UNIQUE,
  NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) DEFAULT NULL,
  ADDRESS VARCHAR(255),
  PHONE VARCHAR(20),
  CASHBACK DECIMAL(20, 2) NOT NULL DEFAULT 0  
);
