CREATE DATABASE IF NOT EXISTS CLIENTS;
USE CLIENTS;

CREATE TABLE IF NOT EXISTS CLIENTS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  address VARCHAR(255),
  phone VARCHAR(20)
);
